@startuml
autonumber

FA실 -> 정산관리자: 유통사 정산관리 데이터 요청
정산관리자 -> FA실 : 유통사 정산관리 데이터 응답

마켓봄 -> 정산관리자: 유통사 계좌 초기화 요청
정산관리자 -> 정산관리자:  유통사 계좌 초기화
FA실 -> 정산관리자: **초기화 이전 계좌**로 확인 후 정산완료 클릭
정산관리자 -> 정산관리자:  정산완료처리
FA실 -> 정산관리자: [새로고침] 유통사 정산관리 데이터 요청
정산관리자 -> FA실 : 유통사 정산관리 데이터 응답\n(정산상태: 정산완료, 정산계좌: 빈값)
@enduml